title = "Production configuration"

[wallet]
private_key = ""

[bind]
http_interface = "127.0.0.1"
http_port = 1234
http_read_timeout_ms = 10000
http_write_timeout_ms = 10000
http_max_header_bytes = 8192

[eth]
url = "wss://web3.oasiscloud.io/ws"

