##################################
# Docker image deployment pipeline
##################################

common_tools_plugin: &common_tools_plugin
  oasislabs/private-oasis-buildkite-tools#v0.5.0: ~

steps:
  - label: Generate a set of generic checks
    command: .buildkite/common/pipelines/generic_checks.sh
    plugins:
      - *common_tools_plugin

  # This label must be kept in sync with the label used un runtime-ethereum,
  # which is used to download the artifact produced here.
  - label: Build
    branches: "*"
    command:
      - .buildkite/scripts/docker_build.sh
      - buildkite-agent artifact upload oasis-gateway
    env:
      GOPROXY: https://proxy.golang.org/
    timeout_in_minutes: 20
    retry:
      automatic:
        # Retry if Agent has been forcefully terminated and communication was lost.
        - exit_status: -1
          limit: 3
        # Retry if Agent has been forced to shut down.
        - exit_status: 255
          limit: 3

  - label: Run component tests
    branches: "*"
    command:
      - .buildkite/scripts/docker_run_component_tests.sh
    env:
      GOPROXY: https://proxy.golang.org/
    timeout_in_minutes: 20
    retry:
      automatic:
        # Retry if Agent has been forcefully terminated and communication was lost.
        - exit_status: -1
          limit: 3
        # Retry if Agent has been forced to shut down.
        - exit_status: 255
          limit: 3

  - label: Build context
    branches: master
    command:
      - .buildkite/scripts/build_context.sh
    artifact_paths:
      - /tmp/context.tar.gz
    env:
      GOPROXY: https://proxy.golang.org/
    timeout_in_minutes: 20
    retry:
      automatic:
        # Retry if Agent has been forcefully terminated and communication was lost.
        - exit_status: -1
          limit: 3
        # Retry if Agent has been forced to shut down.
        - exit_status: 255
          limit: 3

  - wait

  - label: ":rocket: Publish docker image"
    trigger: private-ops-oasis-gateway-publish-image
    async: true
    branches: master
    build:
      message: "${BUILDKITE_MESSAGE}"
      env:
        OASIS_GATEWAY_JOB_ID: "${BUILDKITE_JOB_ID}"
        OASIS_GATEWAY_COMMIT: "${BUILDKITE_COMMIT}"
        OASIS_GATEWAY_BRANCH: "${BUILDKITE_BRANCH}"
